### PR TITLE
🐛(layout) fix panel transitions and resize handling

### LINKED ISSUE #113: 🐛(layout) bug when resizing screen + we see the animation of left and right panel
- Currently, when we resize the screen we see the two panels reposition themselves correctly with their transitions.
- When switching from responsive to desktop and vice versa, the left panel is completely buggy.

### PR DESCRIPTION
**Pull request by PanchoutNathan**
- Added a class to disable transitions during window resizing to prevent mobile panels from being visible.
- Updated the MainLayout component to manage resizing state and optimize panel visibility.
- Enhanced transition effects for left and right panels for smoother animations.
- Refactored the useResponsive hook to improve performance and responsiveness.

close #113 #93

### CODE REVIEW

File: src/components/layout/MainLayout.tsx [hunk 1]
```diff
@@ -48,7 +49,43 @@ export const MainLayout = ({
...
+    return () => {
+      window.removeEventListener("resize", handleResizeStart);
+
+      if (resizeTimeoutRef.current) {
+        clearTimeout(resizeTimeoutRef.current);
+      }
+    };
+  }, []);
+
+  // We need to have two different states for the left panel, we want to always keep the
```
Comment (NathanVss) [inline src/components/layout/MainLayout.tsx:80]: Broken comments, first line is dup

File: src/hooks/useResponsive.tsx [hunk 2]
```diff
@@ -1,30 +1,65 @@
...
     };
-  }, []);
+  }, [responsiveStates]);
 
-  const isMobile = width <= mobile;
-  const isTablet = width <= tablet;
-  const isDesktop = width > tablet;
-
-  return { isMobile, isTablet, isDesktop };
+  return {
```
Comment (NathanVss) [inline src/hooks/useResponsive.tsx:62]:
```
return responsiveStates;
```

**Review by NathanVss — APPROVED** [review]
Yaayy
